### ISSUE TITLE
When will the specific code be published?

### ISSUE THREAD

**Issue by Ephemeral2333** [dengq7/Sketchy-3DIS#1]
Hello. Thank you for your work, when can I publish the full code? This will be of great help to my work, thanks

**Comment by dengq7** [comment]
We have released complete codes already. Please check the "SPFormer" subfolder for the ScanNetV2 dataset and the "ISBNet" subfolder for the S3DIS dataset, respectively.

**Comment by Ephemeral2333** [comment]
Hello, thank you very much for the code, but I still have some problems in SPFormer folder:

1. In the scannetv2.py code
`    def load(self, filename):
        if self.with_normal:
            normal = torch.load(filename.replace(self.suffix, "_normals.pth"), weights_only=False)
        else:
            normal = None
`
The normals.pth file is used here, but the data preprocessing does not seem to generate the file.

2. Meanwhile, in the following code
`
        if self.with_label:
            return torch.load(filename, weights_only=False) + (normal, )
        else:
            xyz, rgb, superpoint = torch.load(filename, weights_only=False)
            dummy_sem_label = np.zeros(xyz.shape[0], dtype=np.float32)
            dummy_inst_label = np.zeros(xyz.shape[0], dtype=np.float32)
            return xyz, rgb, superpoint, dummy_sem_label, dummy_inst_label, normal
`
According to data preprocessing, it seems that superpoint is not read from this file, but should be a special .pth file under the superpoint folder.

3. After I changed the above error, I encountered another issue with floating point exception (core dumped) which I cannot solve.

So I would like to ask if it is a code upload error? If so, I hope it can be corrected, thank you very much.

**Comment by dengq7** [comment]
Thanks for your questions. We have supplemented the preprocessing for obtaining the normals. Please refer to the README and find the codes at https://github.com/dengq7/Sketchy-3DIS/tree/main/SPFormer/data/scannetv2 and https://github.com/dengq7/Sketchy-3DIS/tree/main/ISBNet/data/s3dis.
